// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA3FGdRH9aR0OYDh6Cmx7V2_rOXmN1P8w',
    appId: '1:440477195923:web:bce7658c5c0e64020df766',
    messagingSenderId: '440477195923',
    projectId: 'fir-tutorial-12a81',
    authDomain: 'fir-tutorial-12a81.firebaseapp.com',
    storageBucket: 'fir-tutorial-12a81.firebasestorage.app',
    measurementId: 'G-K4RMY4JEET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQT1Op2K_dqwueWmjn13J-vlaDZ0FGgmw',
    appId: '1:440477195923:android:6ceaf638ced14ee20df766',
    messagingSenderId: '440477195923',
    projectId: 'fir-tutorial-12a81',
    storageBucket: 'fir-tutorial-12a81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFFq3vKdk-7zph3BV9mVbmdJmCB_FoZ_A',
    appId: '1:440477195923:ios:1e54ae2f0a0ab4550df766',
    messagingSenderId: '440477195923',
    projectId: 'fir-tutorial-12a81',
    storageBucket: 'fir-tutorial-12a81.firebasestorage.app',
    iosBundleId: 'com.aasthasudan.untitled6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFFq3vKdk-7zph3BV9mVbmdJmCB_FoZ_A',
    appId: '1:440477195923:ios:526d02389406ecb40df766',
    messagingSenderId: '440477195923',
    projectId: 'fir-tutorial-12a81',
    storageBucket: 'fir-tutorial-12a81.firebasestorage.app',
    iosBundleId: 'com.example.untitled6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA3FGdRH9aR0OYDh6Cmx7V2_rOXmN1P8w',
    appId: '1:440477195923:web:fe95c76a413465420df766',
    messagingSenderId: '440477195923',
    projectId: 'fir-tutorial-12a81',
    authDomain: 'fir-tutorial-12a81.firebaseapp.com',
    storageBucket: 'fir-tutorial-12a81.firebasestorage.app',
    measurementId: 'G-DN8KMBHRY3',
  );

}